fun test() {
    try { } catch (e: Exception = Exception()) { }
}